Task 2
js-tasks-ru/js-20201030_kletchatii0 pull request #2
Opened 2020-11-03 22:43 UTC by mikenai

2020-11-03 23:41 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
Первая задача
+ should return sum of numbers
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-04 06:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
Первая задача
- should return sum of numbers
```

2020-11-04 14:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-04 18:41 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return param == 'desc' ? a.reverse() : a;
Есть несколько замечаний:
* не используйте короткие имена, такие как `a`, они не дают ынформации о том какие данные мы собираемся в них хранить
* `let a` на самом деле должно быть объявлено через `const a` - помните почему?
* было бы неплохо избавиться от `reverse` - так как это двойная работа (повторная итерация по массиву). Было бы неплохо сортировать сразу в нужном порядке

2020-11-04 18:42 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-11-04 18:47 UTC, mikenai commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return param == 'desc' ? a.reverse() : a;
done

2020-11-04 18:48 UTC, mikenai commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return param == 'desc' ? a.reverse() : a;
короткие имена это из golang у меня

2020-11-04 19:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-06 14:50 UTC, dosandk approved these changes

2020-11-06 14:50 UTC, merged